/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uv.es.ligaajedrez;

import javax.swing.JFrame;
import lombok.extern.slf4j.Slf4j;

/**
 *
 * @author Ezzedine
 */
@Slf4j
public class Jugador extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    private Login login;
    public Jugador() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jf_reserva = new javax.swing.JFrame();
        jp_reserva = new javax.swing.JPanel();
        jl_rSede = new javax.swing.JLabel();
        jl_nSede = new javax.swing.JLabel();
        jTF_nSede = new javax.swing.JTextField();
        jl_nom_1_jugador = new javax.swing.JLabel();
        jTF_nombre1jug = new javax.swing.JTextField();
        jl_fPartida = new javax.swing.JLabel();
        jTF_fechaPartida = new javax.swing.JTextField();
        jb_reservar = new javax.swing.JButton();
        jb_cancel = new javax.swing.JButton();
        jTF_horarioPartida = new javax.swing.JTextField();
        jl_hPartida = new javax.swing.JLabel();
        jb_disponibilidadHora = new javax.swing.JButton();
        jb_disponibilidadDia = new javax.swing.JButton();
        jTF_nombre2jugador = new javax.swing.JTextField();
        jl_nom_2_jugador = new javax.swing.JLabel();
        jTF_nombreEntrenador = new javax.swing.JTextField();
        jl_nEntrenador = new javax.swing.JLabel();
        jf_resultadosPartida = new javax.swing.JFrame();
        jp_resultadosPartida = new javax.swing.JPanel();
        jl_rSede1 = new javax.swing.JLabel();
        jl_nom_1_jugador1 = new javax.swing.JLabel();
        jTF_nombre1jug1 = new javax.swing.JTextField();
        jl_disputacionP = new javax.swing.JLabel();
        jTF_disputacionP = new javax.swing.JTextField();
        jb_guardar = new javax.swing.JButton();
        jb_cancel1 = new javax.swing.JButton();
        jTF_tPartida = new javax.swing.JTextField();
        jl_tPartida = new javax.swing.JLabel();
        jTF_nombre2jugador1 = new javax.swing.JTextField();
        jl_nom_2_jugador1 = new javax.swing.JLabel();
        jTF_nombreGanador = new javax.swing.JTextField();
        jl_nGanador = new javax.swing.JLabel();
        jf_aSede = new javax.swing.JFrame();
        jp_aSede = new javax.swing.JPanel();
        jl_aSede = new javax.swing.JLabel();
        jl_nSede1 = new javax.swing.JLabel();
        jTF_nSede1 = new javax.swing.JTextField();
        jl_nom_1_jugador2 = new javax.swing.JLabel();
        jTF_nombre1jug2 = new javax.swing.JTextField();
        jl_fPartida1 = new javax.swing.JLabel();
        jTF_fechaPartida1 = new javax.swing.JTextField();
        jb_Asignar = new javax.swing.JButton();
        jb_cancel2 = new javax.swing.JButton();
        jTF_horarioPartida1 = new javax.swing.JTextField();
        jl_hPartida1 = new javax.swing.JLabel();
        jb_disponibilidadHora1 = new javax.swing.JButton();
        jb_disponibilidadDia1 = new javax.swing.JButton();
        jTF_nombreEntrenador1jugador = new javax.swing.JTextField();
        jl_nEntrenador1jugador = new javax.swing.JLabel();
        jl_nFed = new javax.swing.JLabel();
        jTF_nFed = new javax.swing.JTextField();
        jTF_club_1_jugador = new javax.swing.JTextField();
        jl_club_1_jugador = new javax.swing.JLabel();
        jl_d1Jugador = new javax.swing.JLabel();
        jTF_nombreEntrenador2jugador = new javax.swing.JTextField();
        jl_nEntrenador2jugador = new javax.swing.JLabel();
        jTF_club_2_jugador = new javax.swing.JTextField();
        jl_club_2_jugador = new javax.swing.JLabel();
        jl_d2Jugador = new javax.swing.JLabel();
        jl_nom2jugador = new javax.swing.JLabel();
        jTF_nombre2jug = new javax.swing.JTextField();
        jf_infantiles = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jb_Asignar1 = new javax.swing.JButton();
        jb_cancel3 = new javax.swing.JButton();
        Jugador = new javax.swing.JPanel();
        jl_jugador = new javax.swing.JLabel();
        jb_reservaSede = new javax.swing.JButton();
        jb_infantiles = new javax.swing.JButton();
        jb_rPartida = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        jf_reserva.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_reserva.setBackground(new java.awt.Color(204, 102, 0));

        jl_rSede.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_rSede.setForeground(new java.awt.Color(255, 255, 255));
        jl_rSede.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_rSede.setText("Realizar Reserva de Sede");
        jl_rSede.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jp_reservaLayout = new javax.swing.GroupLayout(jp_reserva);
        jp_reserva.setLayout(jp_reservaLayout);
        jp_reservaLayout.setHorizontalGroup(
            jp_reservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_reservaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_rSede, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_reservaLayout.setVerticalGroup(
            jp_reservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_reservaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jl_rSede, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jl_nSede.setText("Nombre de Sede:");

        jTF_nSede.setText("Lorena ");
        jTF_nSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_nSedeActionPerformed(evt);
            }
        });

        jl_nom_1_jugador.setText("Nombre primer jugador");

        jTF_nombre1jug.setText("Iborra López");

        jl_fPartida.setText("Fecha de partida:");

        jTF_fechaPartida.setText("10/05/2009");

        jb_reservar.setBackground(new java.awt.Color(0, 153, 255));
        jb_reservar.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jb_reservar.setForeground(new java.awt.Color(255, 255, 255));
        jb_reservar.setText("Reservar");
        jb_reservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_reservarActionPerformed(evt);
            }
        });

        jb_cancel.setBackground(new java.awt.Color(0, 153, 255));
        jb_cancel.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jb_cancel.setForeground(new java.awt.Color(255, 255, 255));
        jb_cancel.setText("Cancelar");
        jb_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancelActionPerformed(evt);
            }
        });

        jTF_horarioPartida.setText("17:00");

        jl_hPartida.setText("Horario de partida:");

        jb_disponibilidadHora.setBackground(new java.awt.Color(0, 153, 255));
        jb_disponibilidadHora.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jb_disponibilidadHora.setForeground(new java.awt.Color(255, 255, 255));
        jb_disponibilidadHora.setText("consulta disponibilidad");
        jb_disponibilidadHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_disponibilidadHoraActionPerformed(evt);
            }
        });

        jb_disponibilidadDia.setBackground(new java.awt.Color(0, 153, 255));
        jb_disponibilidadDia.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jb_disponibilidadDia.setForeground(new java.awt.Color(255, 255, 255));
        jb_disponibilidadDia.setText("consulta disponibilidad");
        jb_disponibilidadDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_disponibilidadDiaActionPerformed(evt);
            }
        });

        jTF_nombre2jugador.setText("Alex Garcia");
        jTF_nombre2jugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_nombre2jugadorActionPerformed(evt);
            }
        });

        jl_nom_2_jugador.setText("Nombre segundo jugador");

        jTF_nombreEntrenador.setText("Alex Garcia");
        jTF_nombreEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_nombreEntrenadorActionPerformed(evt);
            }
        });

        jl_nEntrenador.setText("Nombre entrenador");

        javax.swing.GroupLayout jf_reservaLayout = new javax.swing.GroupLayout(jf_reserva.getContentPane());
        jf_reserva.getContentPane().setLayout(jf_reservaLayout);
        jf_reservaLayout.setHorizontalGroup(
            jf_reservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_reserva, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jf_reservaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jf_reservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_reservaLayout.createSequentialGroup()
                        .addComponent(jl_nEntrenador)
                        .addGap(18, 18, 18)
                        .addComponent(jTF_nombreEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jf_reservaLayout.createSequentialGroup()
                        .addComponent(jl_nSede)
                        .addGap(18, 18, 18)
                        .addComponent(jTF_nSede, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_fPartida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_fechaPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jb_disponibilidadDia, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jf_reservaLayout.createSequentialGroup()
                        .addComponent(jl_hPartida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTF_horarioPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_disponibilidadHora, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jf_reservaLayout.createSequentialGroup()
                        .addGroup(jf_reservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jf_reservaLayout.createSequentialGroup()
                                .addComponent(jl_nom_1_jugador)
                                .addGap(18, 18, 18)
                                .addComponent(jTF_nombre1jug, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45)
                                .addComponent(jl_nom_2_jugador))
                            .addGroup(jf_reservaLayout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(jb_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jb_reservar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_nombre2jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jf_reservaLayout.setVerticalGroup(
            jf_reservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_reservaLayout.createSequentialGroup()
                .addComponent(jp_reserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jf_reservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nSede)
                    .addComponent(jTF_nSede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_fPartida)
                    .addComponent(jTF_fechaPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_disponibilidadDia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jf_reservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_hPartida)
                    .addComponent(jTF_horarioPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_disponibilidadHora))
                .addGap(18, 18, 18)
                .addGroup(jf_reservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nom_1_jugador)
                    .addComponent(jTF_nombre1jug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_nom_2_jugador)
                    .addComponent(jTF_nombre2jugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jf_reservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nEntrenador)
                    .addComponent(jTF_nombreEntrenador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jf_reservaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_reservar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        jf_resultadosPartida.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_resultadosPartida.setBackground(new java.awt.Color(204, 102, 0));

        jl_rSede1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_rSede1.setForeground(new java.awt.Color(255, 255, 255));
        jl_rSede1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_rSede1.setText("Introducir los resultados de la partida ");
        jl_rSede1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jp_resultadosPartidaLayout = new javax.swing.GroupLayout(jp_resultadosPartida);
        jp_resultadosPartida.setLayout(jp_resultadosPartidaLayout);
        jp_resultadosPartidaLayout.setHorizontalGroup(
            jp_resultadosPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_resultadosPartidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_rSede1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_resultadosPartidaLayout.setVerticalGroup(
            jp_resultadosPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_resultadosPartidaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jl_rSede1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jl_nom_1_jugador1.setText("Nombre primer jugador");

        jTF_nombre1jug1.setText("Iborra López");

        jl_disputacionP.setText("Fecha de disputacion:");

        jTF_disputacionP.setText("10/05/2009");

        jb_guardar.setBackground(new java.awt.Color(0, 153, 255));
        jb_guardar.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jb_guardar.setForeground(new java.awt.Color(255, 255, 255));
        jb_guardar.setText("Guardar");
        jb_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_guardarActionPerformed(evt);
            }
        });

        jb_cancel1.setBackground(new java.awt.Color(0, 153, 255));
        jb_cancel1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jb_cancel1.setForeground(new java.awt.Color(255, 255, 255));
        jb_cancel1.setText("Cancelar");
        jb_cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancel1ActionPerformed(evt);
            }
        });

        jTF_tPartida.setText("2 hr");
        jTF_tPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_tPartidaActionPerformed(evt);
            }
        });

        jl_tPartida.setText("Tiempo de partida");

        jTF_nombre2jugador1.setText("Alex Garcia");
        jTF_nombre2jugador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_nombre2jugador1ActionPerformed(evt);
            }
        });

        jl_nom_2_jugador1.setText("Nombre segundo jugador");

        jTF_nombreGanador.setText("Alex Garcia");
        jTF_nombreGanador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_nombreGanadorActionPerformed(evt);
            }
        });

        jl_nGanador.setText("Nombre ganador");

        javax.swing.GroupLayout jf_resultadosPartidaLayout = new javax.swing.GroupLayout(jf_resultadosPartida.getContentPane());
        jf_resultadosPartida.getContentPane().setLayout(jf_resultadosPartidaLayout);
        jf_resultadosPartidaLayout.setHorizontalGroup(
            jf_resultadosPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_resultadosPartida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jf_resultadosPartidaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jf_resultadosPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_nom_1_jugador1)
                    .addComponent(jl_disputacionP)
                    .addComponent(jl_nGanador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jf_resultadosPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jf_resultadosPartidaLayout.createSequentialGroup()
                        .addComponent(jb_cancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(jb_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTF_nombreGanador, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jf_resultadosPartidaLayout.createSequentialGroup()
                        .addComponent(jTF_disputacionP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jl_tPartida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTF_tPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jf_resultadosPartidaLayout.createSequentialGroup()
                        .addComponent(jTF_nombre1jug1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jl_nom_2_jugador1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_nombre2jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jf_resultadosPartidaLayout.setVerticalGroup(
            jf_resultadosPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_resultadosPartidaLayout.createSequentialGroup()
                .addComponent(jp_resultadosPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jf_resultadosPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nom_1_jugador1)
                    .addComponent(jTF_nombre1jug1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_nom_2_jugador1)
                    .addComponent(jTF_nombre2jugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jf_resultadosPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF_disputacionP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_tPartida)
                    .addComponent(jTF_tPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_disputacionP))
                .addGap(25, 25, 25)
                .addGroup(jf_resultadosPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nGanador)
                    .addComponent(jTF_nombreGanador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jf_resultadosPartidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_cancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jf_aSede.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_aSede.setBackground(new java.awt.Color(204, 102, 0));

        jl_aSede.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_aSede.setForeground(new java.awt.Color(255, 255, 255));
        jl_aSede.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_aSede.setText("Asignacion de sede para partidas del torneo");
        jl_aSede.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jp_aSedeLayout = new javax.swing.GroupLayout(jp_aSede);
        jp_aSede.setLayout(jp_aSedeLayout);
        jp_aSedeLayout.setHorizontalGroup(
            jp_aSedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_aSedeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_aSede)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_aSedeLayout.setVerticalGroup(
            jp_aSedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_aSedeLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jl_aSede, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jl_nSede1.setText("Nombre de Sede:");

        jTF_nSede1.setText("san jose");
        jTF_nSede1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_nSede1ActionPerformed(evt);
            }
        });

        jl_nom_1_jugador2.setText("Nombre  jugador");

        jTF_nombre1jug2.setText("Iborra López");

        jl_fPartida1.setText("Fecha de partida:");

        jTF_fechaPartida1.setText("10/05/2009");

        jb_Asignar.setBackground(new java.awt.Color(0, 153, 255));
        jb_Asignar.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jb_Asignar.setForeground(new java.awt.Color(255, 255, 255));
        jb_Asignar.setText("Asignar");
        jb_Asignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_AsignarActionPerformed(evt);
            }
        });

        jb_cancel2.setBackground(new java.awt.Color(0, 153, 255));
        jb_cancel2.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jb_cancel2.setForeground(new java.awt.Color(255, 255, 255));
        jb_cancel2.setText("Cancelar");
        jb_cancel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancel2ActionPerformed(evt);
            }
        });

        jTF_horarioPartida1.setText("17:00");

        jl_hPartida1.setText("Horario de partida:");

        jb_disponibilidadHora1.setBackground(new java.awt.Color(0, 153, 255));
        jb_disponibilidadHora1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jb_disponibilidadHora1.setForeground(new java.awt.Color(255, 255, 255));
        jb_disponibilidadHora1.setText("consulta disponibilidad");
        jb_disponibilidadHora1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_disponibilidadHora1ActionPerformed(evt);
            }
        });

        jb_disponibilidadDia1.setBackground(new java.awt.Color(0, 153, 255));
        jb_disponibilidadDia1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jb_disponibilidadDia1.setForeground(new java.awt.Color(255, 255, 255));
        jb_disponibilidadDia1.setText("consulta disponibilidad");
        jb_disponibilidadDia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_disponibilidadDia1ActionPerformed(evt);
            }
        });

        jTF_nombreEntrenador1jugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_nombreEntrenador1jugadorActionPerformed(evt);
            }
        });

        jl_nEntrenador1jugador.setText("Nombre entrenador");

        jl_nFed.setText("Nombre de federacion:");

        jTF_nFed.setText("Federacion de valencia");
        jTF_nFed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_nFedActionPerformed(evt);
            }
        });

        jTF_club_1_jugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_club_1_jugadorActionPerformed(evt);
            }
        });

        jl_club_1_jugador.setText("Club   ");

        jl_d1Jugador.setText("Datos primer jugador");

        jTF_nombreEntrenador2jugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_nombreEntrenador2jugadorActionPerformed(evt);
            }
        });

        jl_nEntrenador2jugador.setText("Nombre entrenador");

        jTF_club_2_jugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_club_2_jugadorActionPerformed(evt);
            }
        });

        jl_club_2_jugador.setText("Club   ");

        jl_d2Jugador.setText("Datos primer jugador");

        jl_nom2jugador.setText("Nombre  jugador");

        jTF_nombre2jug.setText("Iborra López");

        javax.swing.GroupLayout jf_aSedeLayout = new javax.swing.GroupLayout(jf_aSede.getContentPane());
        jf_aSede.getContentPane().setLayout(jf_aSedeLayout);
        jf_aSedeLayout.setHorizontalGroup(
            jf_aSedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_aSede, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jf_aSedeLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jf_aSedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jl_d2Jugador)
                    .addGroup(jf_aSedeLayout.createSequentialGroup()
                        .addComponent(jl_nom2jugador)
                        .addGap(18, 18, 18)
                        .addComponent(jTF_nombre2jug, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jl_club_2_jugador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_club_2_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jf_aSedeLayout.createSequentialGroup()
                        .addComponent(jl_nEntrenador2jugador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_nombreEntrenador2jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jl_d1Jugador)
                    .addGroup(jf_aSedeLayout.createSequentialGroup()
                        .addComponent(jl_nom_1_jugador2)
                        .addGap(18, 18, 18)
                        .addComponent(jTF_nombre1jug2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jl_club_1_jugador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_club_1_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jf_aSedeLayout.createSequentialGroup()
                        .addComponent(jl_nEntrenador1jugador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_nombreEntrenador1jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jf_aSedeLayout.createSequentialGroup()
                        .addComponent(jl_nFed)
                        .addGap(18, 18, 18)
                        .addComponent(jTF_nFed, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jf_aSedeLayout.createSequentialGroup()
                        .addComponent(jl_nSede1)
                        .addGap(18, 18, 18)
                        .addComponent(jTF_nSede1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jl_fPartida1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTF_fechaPartida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jb_disponibilidadDia1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jf_aSedeLayout.createSequentialGroup()
                        .addComponent(jl_hPartida1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTF_horarioPartida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb_disponibilidadHora1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jf_aSedeLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(jb_cancel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jb_Asignar, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        jf_aSedeLayout.setVerticalGroup(
            jf_aSedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_aSedeLayout.createSequentialGroup()
                .addComponent(jp_aSede, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jf_aSedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nFed)
                    .addComponent(jTF_nFed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jf_aSedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nSede1)
                    .addComponent(jTF_nSede1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_fPartida1)
                    .addComponent(jTF_fechaPartida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_disponibilidadDia1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jf_aSedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_hPartida1)
                    .addComponent(jTF_horarioPartida1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_disponibilidadHora1))
                .addGap(18, 18, 18)
                .addComponent(jl_d1Jugador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jf_aSedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nom_1_jugador2)
                    .addComponent(jTF_nombre1jug2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_club_1_jugador)
                    .addComponent(jTF_club_1_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jf_aSedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nEntrenador1jugador)
                    .addComponent(jTF_nombreEntrenador1jugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jl_d2Jugador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jf_aSedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nom2jugador)
                    .addComponent(jTF_nombre2jug, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_club_2_jugador)
                    .addComponent(jTF_club_2_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jf_aSedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_nEntrenador2jugador)
                    .addComponent(jTF_nombreEntrenador2jugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jf_aSedeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_Asignar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_cancel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jf_infantiles.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 102, 0));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Asignacion de responsable para los infantiles");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 653, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jInternalFrame1.setForeground(new java.awt.Color(51, 102, 255));
        jInternalFrame1.setVisible(true);

        jLabel1.setText("Nombre");

        jLabel2.setText("Edad");

        jLabel4.setText("Categoria");

        jLabel5.setText("Clasificación ELO");

        jLabel6.setText("Estado Cuota Anual");

        jTextField1.setText("Aithor Iborra Lopez");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.setText("14");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setText("INFANTIL");

        jTextField4.setEditable(false);
        jTextField4.setText("1602");

        jTextField5.setEditable(false);
        jTextField5.setText("PAGADO");

        jLabel7.setText("Nombre responsable del jugador");

        jTextField6.setText("Paco Iborra Martinez");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jLabel8.setText("DNI Responsable del jugador");

        jTextField7.setText("22445232F");

        jLabel9.setText("Caducidad tarjeta");

        jTextField8.setEditable(false);
        jTextField8.setText("20/07/2021");

        jLabel10.setText("Relacion con jugador");

        jTextField9.setText("padre");
        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jb_Asignar1.setBackground(new java.awt.Color(0, 153, 255));
        jb_Asignar1.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jb_Asignar1.setForeground(new java.awt.Color(255, 255, 255));
        jb_Asignar1.setText("Asignar");
        jb_Asignar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_Asignar1ActionPerformed(evt);
            }
        });

        jb_cancel3.setBackground(new java.awt.Color(0, 153, 255));
        jb_cancel3.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jb_cancel3.setForeground(new java.awt.Color(255, 255, 255));
        jb_cancel3.setText("Cancelar");
        jb_cancel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_cancel3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                            .addComponent(jTextField7))
                        .addGap(36, 36, 36)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField9)))
                .addContainerGap(37, Short.MAX_VALUE))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jb_cancel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jb_Asignar1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_Asignar1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_cancel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jf_infantilesLayout = new javax.swing.GroupLayout(jf_infantiles.getContentPane());
        jf_infantiles.getContentPane().setLayout(jf_infantilesLayout);
        jf_infantilesLayout.setHorizontalGroup(
            jf_infantilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jInternalFrame1)
        );
        jf_infantilesLayout.setVerticalGroup(
            jf_infantilesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jf_infantilesLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin");

        Jugador.setBackground(new java.awt.Color(204, 102, 0));

        jl_jugador.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jl_jugador.setForeground(new java.awt.Color(255, 255, 255));
        jl_jugador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jl_jugador.setText("Jugador");
        jl_jugador.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout JugadorLayout = new javax.swing.GroupLayout(Jugador);
        Jugador.setLayout(JugadorLayout);
        JugadorLayout.setHorizontalGroup(
            JugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JugadorLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jl_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JugadorLayout.setVerticalGroup(
            JugadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JugadorLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jl_jugador, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jb_reservaSede.setBackground(new java.awt.Color(0, 153, 255));
        jb_reservaSede.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jb_reservaSede.setForeground(new java.awt.Color(255, 255, 255));
        jb_reservaSede.setText("Realizar reserva");
        jb_reservaSede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_reservaSedeActionPerformed(evt);
            }
        });

        jb_infantiles.setBackground(new java.awt.Color(0, 153, 255));
        jb_infantiles.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jb_infantiles.setForeground(new java.awt.Color(255, 255, 255));
        jb_infantiles.setText("Asignar responsable a los infanitles");
        jb_infantiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_infantilesActionPerformed(evt);
            }
        });

        jb_rPartida.setBackground(new java.awt.Color(0, 153, 255));
        jb_rPartida.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        jb_rPartida.setForeground(new java.awt.Color(255, 255, 255));
        jb_rPartida.setText("Introducir resultados partida");
        jb_rPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_rPartidaActionPerformed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(0, 153, 255));
        btnExit.setFont(new java.awt.Font("Dialog", 1, 13)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 255, 255));
        btnExit.setText("Volver");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Jugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jb_infantiles, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jb_reservaSede, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jb_rPartida, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Jugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_rPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jb_reservaSede, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jb_infantiles, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_reservaSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_reservaSedeActionPerformed
        this.setVisible(false);                     
        jf_reserva.setSize(876, 400);
        jf_reserva.setVisible(true);        
    }//GEN-LAST:event_jb_reservaSedeActionPerformed

    private void jb_infantilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_infantilesActionPerformed
        this.setVisible(false);
        jf_infantiles.setSize(912, 500);
        jf_infantiles.setVisible(true);
    }//GEN-LAST:event_jb_infantilesActionPerformed

    private void jb_rPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_rPartidaActionPerformed
        this.setVisible(false);
        jf_resultadosPartida.setSize(802, 400);
        jf_resultadosPartida.setVisible(true);        
    }//GEN-LAST:event_jb_rPartidaActionPerformed

    private void jTF_nSedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_nSedeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_nSedeActionPerformed

    private void jb_reservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_reservarActionPerformed
        jf_reserva.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jb_reservarActionPerformed

    private void jb_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancelActionPerformed
        jf_reserva.setVisible(false);
        this.setVisible(true);

    }//GEN-LAST:event_jb_cancelActionPerformed

    private void jb_disponibilidadHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_disponibilidadHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_disponibilidadHoraActionPerformed

    private void jb_disponibilidadDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_disponibilidadDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_disponibilidadDiaActionPerformed

    private void jTF_nombre2jugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_nombre2jugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_nombre2jugadorActionPerformed

    private void jTF_nombreEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_nombreEntrenadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_nombreEntrenadorActionPerformed

    private void jb_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_guardarActionPerformed
        jf_resultadosPartida.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jb_guardarActionPerformed

    private void jb_cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancel1ActionPerformed
        jf_resultadosPartida.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jb_cancel1ActionPerformed

    private void jTF_nombre2jugador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_nombre2jugador1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_nombre2jugador1ActionPerformed

    private void jTF_nombreGanadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_nombreGanadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_nombreGanadorActionPerformed

    private void jTF_tPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_tPartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_tPartidaActionPerformed

    private void jTF_nSede1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_nSede1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_nSede1ActionPerformed

    private void jb_AsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_AsignarActionPerformed
        jf_aSede.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jb_AsignarActionPerformed

    private void jb_cancel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancel2ActionPerformed
        jf_aSede.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jb_cancel2ActionPerformed

    private void jb_disponibilidadHora1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_disponibilidadHora1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_disponibilidadHora1ActionPerformed

    private void jb_disponibilidadDia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_disponibilidadDia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_disponibilidadDia1ActionPerformed

    private void jTF_nombreEntrenador1jugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_nombreEntrenador1jugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_nombreEntrenador1jugadorActionPerformed

    private void jTF_nFedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_nFedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_nFedActionPerformed

    private void jTF_club_1_jugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_club_1_jugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_club_1_jugadorActionPerformed

    private void jTF_nombreEntrenador2jugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_nombreEntrenador2jugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_nombreEntrenador2jugadorActionPerformed

    private void jTF_club_2_jugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_club_2_jugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_club_2_jugadorActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jb_Asignar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_Asignar1ActionPerformed
        jf_infantiles.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jb_Asignar1ActionPerformed

    private void jb_cancel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_cancel3ActionPerformed
        jf_infantiles.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_jb_cancel3ActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        exitAdmin();
    }//GEN-LAST:event_btnExitActionPerformed

    private void exitAdmin() {
     // Navegamos al menu del admin de la aplicación
     dispose();
     Login loginAdmin = new Login();
     loginAdmin.setVisible(true);         
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Jugador;
    private javax.swing.JButton btnExit;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTF_club_1_jugador;
    private javax.swing.JTextField jTF_club_2_jugador;
    private javax.swing.JTextField jTF_disputacionP;
    private javax.swing.JTextField jTF_fechaPartida;
    private javax.swing.JTextField jTF_fechaPartida1;
    private javax.swing.JTextField jTF_horarioPartida;
    private javax.swing.JTextField jTF_horarioPartida1;
    private javax.swing.JTextField jTF_nFed;
    private javax.swing.JTextField jTF_nSede;
    private javax.swing.JTextField jTF_nSede1;
    private javax.swing.JTextField jTF_nombre1jug;
    private javax.swing.JTextField jTF_nombre1jug1;
    private javax.swing.JTextField jTF_nombre1jug2;
    private javax.swing.JTextField jTF_nombre2jug;
    private javax.swing.JTextField jTF_nombre2jugador;
    private javax.swing.JTextField jTF_nombre2jugador1;
    private javax.swing.JTextField jTF_nombreEntrenador;
    private javax.swing.JTextField jTF_nombreEntrenador1jugador;
    private javax.swing.JTextField jTF_nombreEntrenador2jugador;
    private javax.swing.JTextField jTF_nombreGanador;
    private javax.swing.JTextField jTF_tPartida;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton jb_Asignar;
    private javax.swing.JButton jb_Asignar1;
    private javax.swing.JButton jb_cancel;
    private javax.swing.JButton jb_cancel1;
    private javax.swing.JButton jb_cancel2;
    private javax.swing.JButton jb_cancel3;
    private javax.swing.JButton jb_disponibilidadDia;
    private javax.swing.JButton jb_disponibilidadDia1;
    private javax.swing.JButton jb_disponibilidadHora;
    private javax.swing.JButton jb_disponibilidadHora1;
    private javax.swing.JButton jb_guardar;
    private javax.swing.JButton jb_infantiles;
    private javax.swing.JButton jb_rPartida;
    private javax.swing.JButton jb_reservaSede;
    private javax.swing.JButton jb_reservar;
    private javax.swing.JFrame jf_aSede;
    private javax.swing.JFrame jf_infantiles;
    private javax.swing.JFrame jf_reserva;
    private javax.swing.JFrame jf_resultadosPartida;
    private javax.swing.JLabel jl_aSede;
    private javax.swing.JLabel jl_club_1_jugador;
    private javax.swing.JLabel jl_club_2_jugador;
    private javax.swing.JLabel jl_d1Jugador;
    private javax.swing.JLabel jl_d2Jugador;
    private javax.swing.JLabel jl_disputacionP;
    private javax.swing.JLabel jl_fPartida;
    private javax.swing.JLabel jl_fPartida1;
    private javax.swing.JLabel jl_hPartida;
    private javax.swing.JLabel jl_hPartida1;
    private javax.swing.JLabel jl_jugador;
    private javax.swing.JLabel jl_nEntrenador;
    private javax.swing.JLabel jl_nEntrenador1jugador;
    private javax.swing.JLabel jl_nEntrenador2jugador;
    private javax.swing.JLabel jl_nFed;
    private javax.swing.JLabel jl_nGanador;
    private javax.swing.JLabel jl_nSede;
    private javax.swing.JLabel jl_nSede1;
    private javax.swing.JLabel jl_nom2jugador;
    private javax.swing.JLabel jl_nom_1_jugador;
    private javax.swing.JLabel jl_nom_1_jugador1;
    private javax.swing.JLabel jl_nom_1_jugador2;
    private javax.swing.JLabel jl_nom_2_jugador;
    private javax.swing.JLabel jl_nom_2_jugador1;
    private javax.swing.JLabel jl_rSede;
    private javax.swing.JLabel jl_rSede1;
    private javax.swing.JLabel jl_tPartida;
    private javax.swing.JPanel jp_aSede;
    private javax.swing.JPanel jp_reserva;
    private javax.swing.JPanel jp_resultadosPartida;
    // End of variables declaration//GEN-END:variables
}
